# app/auth/application/ports.py
from __future__ import annotations
from typing import Protocol, Iterable, Optional
from dataclasses import dataclass
from ..domain.entities import User, UserId, Email, PasswordHash, UserStatus

# Erros da aplicação (não HTTP)


class NotFound(Exception):
    ...


class AlreadyExists(Exception):
    ...


class UserRepository(Protocol):
    def add(self, user: User) -> None: ...
    def save(self, user: User) -> None: ...
    def get_by_id(self, user_id: UserId) -> User: ...
    def get_by_email(self, email: Email) -> User: ...
    def exists_by_email(self, email: Email) -> bool: ...
    def list(self, *, limit: int = 50, offset: int = 0) -> Iterable[User]: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...
